### ISSUE TITLE
Improve and refactor Peers module

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1008]
- [x] Refactor `Peers.prototype.getConsensus` #1021
- [x] Remove consensus calculation from `Peers.prototype.list` #1014
- [x] Remove argument mutation from `Peers.prototype.list` #1020 
- [x] Improve unit tests for `Peers.prototype.getConsensus`, `Peers.prototype.list`, `Peers.prototype.remove`, `Peers.prototype.update`
