### ISSUE TITLE
Improvements related to swagger

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1143]
We need/can improve following stuff in app which is related to swagger. 

Must to do: 
- [x] Remove unused schema definitions under schema/* files #1159 
- [x] Migrate z-schema files to swagger definitions #1166
- [x] Introduce an endpoint to expose resolved swagger spec to be used in Swagger UI #1163

Good to do: 
- ~Improve swagger param validation to show proper error for body parameters #1298~
- ~Improve param validation logic to merge 400 and 409 status code responses #1299~

**Comment by karmacoma** [comment]
"Must to dos" now done. Handling #1298 and #1299 individually from this issue.
