### ISSUE TITLE
Port changes from 0.9.11 to 1.0.0

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1176]
Where applicable we need to port the changes made by `0.9.11` to `1.0.0`.

Release notes: https://github.com/LiskHQ/lisk/releases/tag/0.9.11

- ~Update LiskHQ/node-sodium version~
- ~Peers module unit tests are failing randomly~
- [x] Fix missing parameter propagation #1269
- [x] Improve quality of transaction pool documentation #1250 
- [x] Wrong logic in loader.__private.sync #1270 
- ~Decouple and remove Lisk UI~
- [x] Improve quality of dapps module documentation _(where still applicable)_ #1251
- [x] Reject blocks receipts with block slot/timestamp out of window #1191
- ~Fix broken npm run test~
- [x] Fix failing tests in test/unit/modules/blocks/verify.js #1227
- [x] Update README.md for 0.9.11 #970
- ~Fix LiskHQ/lisk/test.sh failure~

**Comment by karmacoma** [comment]
All changes now ported.
