### ISSUE TITLE
Review unit test coverage of logic

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1302]
Parent: #1169 

## List of child issues:

- [x] Review unit test coverage for logic/account #1599
- [x] Review unit test coverage for logic/block_reward #1600
- [x] Review unit test coverage for logic/block #1601
- [x] Review unit test coverage for logic/transaction #1602 
- [x] Add unit tests for logic/broadcaster #1625 
- [x] Consistent usage of es6 features in logic implementation #1656 
- [x] Review unit test coverage for logic/transaction_pool #1662 
- [x] Review unit test coverage of logic/vote #1663

**Comment by Tosch110** [comment]
I'd like to have a work how this might be correlated with work on lisk-js. However works on this, please drop a message to me as soon as you start :)

**Comment by ManuGowda** [comment]
@Tosch110 I have taken this issue, just letting you know if you want to discuss anything down the line.
