### ISSUE TITLE
Database layer restructuring

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1306]
The first step in making sure the database layer can be built upon without issues, is to provide the correct structure for all database files and folders, similar to how [pg-promise-demo] does it.

Ideally, this is something that must be done at the beginning of the project, not in the middle.

* On the positive side, the proper res-structuring can be done in smaller steps.
* On the negative side, there are not enough tests in place to be sure that nothing gets broken. However, this issue should be addressed in parallel.

The only middle ground here is to start doing it in small PR-s, step-by-step, till we get there.

I have opened this issue so I can tag+track all the changes related to restructuring the database layer, to implement a strong foundation for all database-related tasks.

[pg-promise-demo]:https://github.com/vitaly-t/pg-promise-demo

### Task List

- [x] Introduce minimum and maximum pool config to override current setting of `0` as minimum pool  #1177
- [x] Move SQL statements to `pg-promise` repos concept to utilize easily in more readable #1178
- [x] Provide the correct structure for all database files and folders #1304
- [x] Move the entire `./sql` folder into `./db/sql/init` and add initial documentation for the db folder contents #1309 
- [x] Update `Gruntfile.js` to deploy all SQL in a generic way
- [x] Introducing generic support for SQL files for database repositories
- [x] Add ability to tell when in production/packaged mode #1323
- [x] Improve the SQL loader and cleanup loading code #1372 
- [x] Rewrite class `Migrator` from scratch, to make use of all SQL files and repositories consistent throughout the project #1426

**Comment by karmacoma** [comment]
Closed by #1304

**Comment by vitaly-t** [comment]
Next on the agenda...

* Rewriting class `Migrator` from scratch, to make use of all SQL files and repositories consistent throughout the project.
* Updating `Gruntfile.js` to deploy all SQL in a generic way
* Introducing generic support for SQL files for database repositories

**Comment by vitaly-t** [comment]
This PR addresses the last 3 items: https://github.com/LiskHQ/lisk/pull/1358

**Comment by karmacoma** [comment]
@vitaly-t Ok thanks.

Normally we create such a parent issue with a task list linking to individual child issues. This issue is then used to encompass the tasks which will achieve a wider goal, such as db layer restructuring.

Each child issue then has its own feature branch, e.g. `1234-rewrite_migrator`

This way we keep our PRs strictly isolated to the individual issue being tackled.

It may sound intensive, but with many contributors, this is how we normally maintain discipline.

However, I would say you continue as you proposed, so that we can then close this issue 👍

**Comment by vitaly-t** [comment]
Cheers, let's close this issue and start it clean-slate, with smaller-scope issues ;)

**Comment by karmacoma** [comment]
#1376 Refactor database repositories was detached from this issue.

Original task list now complete.
