### ISSUE TITLE
Enable all possible eslint rules from main and test .eslintrc config

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1485]
### Expected behavior
Turned off `eslint` rules should be fixed to ensure code quality and to be able to use latest ECMA 6 features.
### Actual behavior
Bunch of `eslint` rules were turned off during the `eslint` integration to `1.0.0`, this issue will address all the possible turned off rules.
- [x] Fix plug-in rules - #1486 
- [x] Mocha handle done callback and no exclusive tests - #1492
- [x] Root eslint rules with zero errors - #1515
- [x] Root eslint auto fix errors - #1520
- [x] Mocha no identical title - #1496
- [x] Mocha no pending and skipped tests - #1497
- [x] Mocha no nested tests and no top level hooks #1499
- [x] Mocha no synchronous tests - #1501
- [x] Batch 7 of eslint error fixes - #1535

### Steps to reproduce
In root `.eslintrc.json` under `rules` section turn on the rules and run `npm run lint` to see the errors/warnings

## Manual fix
- "array-callback-return": 38
- [x] "block-scoped-var": 7
- "camelcase": 731
- "consistent-return": 220
- [x] "default-case": 5
- "eqeqeq": 27
- "global-require": 69
- "guard-for-in": 2
- "generator-star-spacing": 2
- "max-len": 94
- "new-cap": 176
- [x] "newline-per-chained-call": 0
- "no-bitwise": 13
- [x] "no-console": 28
- [x] "no-loop-func": 8
- [x] "no-multi-assign": 7
- "no-nested-ternary": 8
- "no-new": 26
- "no-param-reassign": 410
- "no-plusplus": 117
- "no-prototype-builtins": 6
- "no-restricted-globals": 9
- [x] "no-restricted-properties": 2
- "no-restricted-syntax": 7
- "no-shadow": 321
- "no-template-curly-in-string": 58
- "no-throw-literal": 29
- "no-underscore-dangle": 161
- "no-unused-expressions": 913
- "no-use-before-define": 45
- [x] "no-useless-escape": 2
- "prefer-destructuring": 221
- "prefer-rest-params": 5
- "radix": 76
- [x] "require-jsdoc": 0
- "strict": 286
- "vars-on-top": , 1022
- "wrap-iife": , 2

## Auto fix using `npm run lint:fix`
- [x] "comma-dangle": 2899
- [x] "no-else-return": 150
- [x] "lines-around-directive": 290
- "space-before-function-paren": 2180
- [x] "dot-notation": 20
- "no-var": 4519
- [x] "object-shorthand": 668
- [x] "prefer-arrow-callback": 1062

## Warnings
- "func-names": 2182

**Comment by ManuGowda** [comment]
The eslint rules in the bullet point will be addressed here #1597
