### ISSUE TITLE
Backport 0.9.12 changes to 1.0.0

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1666]
Backport changes made for 0.9.12 patch release.

### Task List

- [x] On transaction apply and undo, do not reset state of an account https://github.com/LiskHQ/lisk/pull/1349 - (#1667)
- [x] Bug in TransactionPool.transactionInPool https://github.com/LiskHQ/lisk/pull/1360 - (#1670)
- [x] Logs are not verbose enough for apply unconfirmed transaction https://github.com/LiskHQ/lisk/pull/1367 - (#1664)
- [x] Error on applyUnconfirmed step is neglected in chain/applyBlock a5043616e75bc01dcf1f251373f6b88297b17713 - (Requires further work, as described in #1652)
- [x] Ensure forge and sync process exclusiveness d305c88ef9893d09946f477f278076e8ec626c99 - (#1659)
- [x] Duplicated transaction in queues corrupts unconfirmed state 7c20780eebe431ffcbdcdf8a7c4652740ca03e0f - (#1661)
- [x] Re-receive transactions from deleted block ac2498d4530a77da9541e2a3fa0a791ea33a2ace - (Already done in 1.0.0)
- [x] Update dependencies with vulnerabilities 62451437495f3edb9fe18e510227a71b39cc80cf - (Already done in 1.0.0)
- [x] Transaction pool unit tests fix aad735c10a5c269ca1a1acf6cebf8e19ddac7765 - (#1661)
- [x] Fix delegate unit tests 1e8018ea92a5515e36b4daaf0b94e2166e48f819 - (#1667)
- [x] Extend stress test by adding extra transaction types d7e16e35c85d2ca16ddffa3adf6634401e624864 - (#1758)
- [x] Re-receive transactions from deleted block d533af33f83b093584e3819db4602095ce2d931a - (Already done in 1.0.0)

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0
