### ISSUE TITLE
Review unit test coverage of modules

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#1708]
Parent #1169 
- [x] account: incomplete test
- [x] blocks: all test are pending (#1711)
- [x] cache: incomplete test
- [ ] dapps: all test are pending
- [x] delegates: most test are pending
- [x] loader: most test are pending (refactor code base due to nested functions)
- [x] multisignature: all tests are pending (#1723)
- [x] node: most test are pending (#2446)
~~- [ ] peers: tests __private functions are pending~~
- [x] signatures: all test are pending (#2445)
- [ ] transactions: some tests are pending

### Which version(s) does this affect? (Environment, OS, etc...)
`*.*.*`

**Comment by MaciejBaj** [comment]
Peers module is currently being extracted to become a part of Lisk Elements, where all of the logic will be fully covered. It's not necessary to cover its private functions in Lisk Core. I am removing it from the list.
