### ISSUE TITLE
Backport 0.9.14 changes to 1.0.0

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1972]
Backport changes made for 0.9.14 patch release.

### Task List:

- [x] Backport inconsistent behavior between syncing and snapshotting #1976
- [x] Backport code changes for handling inert transactions #1977
- [x] Backport remove exceptions added in 0.9.13 for mainnet #1978

**Comment by SargeKhan** [comment]
All child issues are solved.
