### ISSUE TITLE
Backport 0.9.16 changes to 1.0.0

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2098]
Review if those issues already fixed in `0.9.16` are still present in `1.0.0` and if yes - backport the corresponding fixes.
### Task list
- [x] Incorrect usage of promises in Chain.prototype.saveBlock https://github.com/LiskHQ/lisk/issues/2101 (`1.0.0-beta.8` not affected)
- [x] Last block is set before block is saved to database https://github.com/LiskHQ/lisk/issues/2102
- [x] Error from modules.round.tick is ignored https://github.com/LiskHQ/lisk/issues/2103 (`1.0.0-beta.8` not affected)
