### ISSUE TITLE
Issues needed to be closed in Lisk-Scripts

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2099]
- [x] Rely on Lisk Core process termination while creating snapshot https://github.com/LiskHQ/lisk-scripts/issues/81
- [x] Ensure created snapshots works https://github.com/LiskHQ/lisk-scripts/issues/80
- [x] Update the path and filename for config migration script https://github.com/LiskHQ/lisk-scripts/issues/66
- [x] Remove updateConfig.js https://github.com/LiskHQ/lisk-scripts/issues/63
- [x] Backport changes for installLisk.sh for pre 1.0.0 branch https://github.com/LiskHQ/lisk-scripts/issues/61
- [x] Update dependent lisk scripts to test lisk migration on core https://github.com/LiskHQ/lisk-scripts/issues/60
- [x] Update lisk_bridge script to stop the node if missed the height https://github.com/LiskHQ/lisk-scripts/issues/85
- [x] Fix installLisk.sh to run configuration migration https://github.com/LiskHQ/lisk-scripts/issues/86
