### ISSUE TITLE
Network test suite improvements

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#2230]
### Expected behavior
There are several improvements of integration tests suite that will improve the overall test suite quality, reliability and determinism.

### Task List

- [x]  (#2332) _network/peers.js_ — make the forging test strict, relying on waiting for a block only after the consensus has been achieved: // Expect some blocks to be forged after 30 seconds
- [x] (#2333) _network/peer_disconnect.js_ — replace hardcoded constants in descriptions with proper explanation: // - 20; + 18 previously held connections
- [x] (#2334) _scenarios/common.js_ — make `restartNode`, `stopNode`, `startNode` asynchronous. Switch `childProcess.execSync` to `childProcess.exec` and utilize the output to verify if the task had been successful or not. Refactor the function usages by removing waiting for actions to succeed in timeout.
- [x] (#2335) _setup/network .js_ — add comments with descriptions for SYNC_MODES
- [x]   (#2331) _peers_blacklist.js_ — clarify and explain the expectation of disconnecting Node from itself Clarify which state (BANNED/CONNECTED) should be checked in the tests
- [x] (#2276) _peers_blacklist.js_ — perform strict tests expectations instead of if conditions using ‘<=’ 
- [x] (#2386) _peers_blacklist.js_ — Remove Peers Blacklist from Network Test suite

**Comment by MaciejBaj** [comment]
The issue has been created as a result of the unclear range of changes introduced in PR #2203.
 I suggest renaming the issue to "Integration test suite improvements", introducing the specific list of changes identified as worthwhile introducing:

- [ ] peers_blacklist.js — perform strict tests expectations instead of if conditions using ‘<=’.
- [ ] peers_blacklist.js — clarify and explain the expectation of disconnecting Node from itself. Clarify which state (BANNED/CONNECTED) should be checked in the tests.
- [ ] network/peers.js — make the forging test strict, relying on waiting for a block only after the consensus has been achieved: // Expect some blocks to be forged after 30 seconds
- [ ] network/peer_disconnect.js — replace hardcoded constants in descriptions with proper explanation: // - 20; + 18 previously held connections
- [ ] scenarios/common.js — make `restartNode`, `stopNode`, `startNode` asynchronous. Switch `childProcess.execSync` to `childProcess.exec` and utilize the output to verify if the task had been successful or not. Refactor the function usages by removing waiting for actions to succeed in timeout.
- [ ] setup/network .js— add comments with descriptions for SYNC_MODES
