### ISSUE TITLE
Refactor API endpoints to follow REST standards

### ISSUE THREAD

**Issue by mfressdorf** [LiskHQ/lisk#225]
The beauty of REST is its expressiveness and as I read through the documentation and had a quick look into the codebase, a lot of those API endpoints are not yet following common REST standards.

Just a few examples out of the API documentation:

```
GET /api/accounts/getBalance?address=<address>
GET /api/accounts/getPublicKey?address=address
GET /api/transactions/get?id=id
```

My proposed solution:

```
GET /api/accounts/:address/balance
GET /api/accounts/:address/publicKey
GET /api/transactions/:id
```

Or something like:

```
GET /api/accounts/:address
GET /api/accounts/:address?fields=balance
GET /api/accounts/:address?fields=publicKey
```

Some good indicators are given in this [article by Vinay Sahni](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api) (that I quickly googled up, probably will update this later on with some more useful references on this matter).

---

Proposal: http://swaggerhub.com/apis/LiskHQ/Lisk/1.0.6 

Related Task List:

- [x] Decouple and remove Lisk UI. #458
- [x] Remove selected dapps functionalties, pending rewrite. #560 
- [x] Remove all insecure POST API endpoints. #457
- [x] Functional tests rewrite. #678
- ~Standardise middleware API responses.~ #674 
- [x] Add new standard middleware for REST API. #857
- ~Implement automated API documentation and playground.~ #240
- ~Implement API versioning.~ #236
- [x] Swagger Integration with Core #899

Endpoint Task List:

- [x] accounts - #903 
- [x] blocks - #861 
- [x] dapps - #866 
- [x] delegates - #878 
- [x] node - #862
- [x] peers - #858
- [x] signatures - #879
- [x] transactions - #872
- [x] votes - #880
- [x] voters - #881

**Comment by fix** [comment]
thanks for this ticket.
related #236 

@karmacoma maybe we can make it on /api/v2/

**Comment by karmacoma** [comment]
Resources:

- https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/
- http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

**Comment by diego-G** [comment]
Guidelines for the draft session https://drive.google.com/open?id=1bg5SOBHMfi4rs_D-8qH0X-ZjQD5QN-fsIyAkazHD2-o

**Comment by diego-G** [comment]
Due to the extensive nature of this action, I will divide the work in modules listed below as a checklist. This will facilitate the follow-up to reviewers.

- [ ] accounts
- [ ] blocks
- [ ] dapps
- [ ] delegate
- [ ] loader
- [ ] multisignature
- [ ] peers
- [ ] signatures
- [ ] transactions
- [ ] transport

**Comment by karmacoma** [comment]
@diego-G: Please note, the following related issues which also need to be addressed:

- [ ] Decouple and remove Lisk UI. #458
- [ ] Remove selected dapps functionalties, pending rewrite. #560
- [ ] Remove all insecure POST API endpoints. #457
- [ ] Implement automated API documentation and playground. #240
- [ ] Implement API versioning. #236

**Comment by karmacoma** [comment]
@Isabello As described in #560, we are keeping certain `dapps` related functionalities:

Therefore in new design spec we will need to make sure to add:

```
GET /dapps/:id <-- For getting an individual application registration
GET /dapps <-- For listing of registered applications
GET /dapps/categories <-- For listing of application categories
```

**Comment by MaciejBaj** [comment]
Following to Diego's suggestion, the work should be split by applying changes one by one following new API redesign 
[model](https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.5).
Some extra work should be done first, as the format of responses is about to change from `success: true/false` pattern into returning error code format.

Created PR's should be done in following order:
- [ ] 1. Set up structure for the new API response format including error codes
- [ ] 2. Apply changes for each new module one by one keeping on mind unit and functional tests rewrite
- [ ] accounts
- [ ] blocks
- [ ] delegates
- [ ] private
- [ ] node
- [ ] peers
- [ ] transactions 
- [ ] votes

**Comment by karmacoma** [comment]
Added @Isabello current proposal to the issue description.
