### ISSUE TITLE
Extensible Data Persistence Model

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2576]
Purpose of this task is to  use a Extended Data Mapper pattern for the database component outlined by the LIP “Introduce new flexible, resilient and modular architecture for Lisk Core”. The proposed model will help to extend and maintain the persistence layer of Lisk Core by being generic, easy to understand and organized.

1. [x] Create basic structure for entities and storage initialization https://github.com/LiskHQ/lisk/issues/2613
2. [x] Create Account entity with CRUD operations and unit tests https://github.com/LiskHQ/lisk/issues/2614
2. [x] Create Block entity with CRUD operations and unit tests https://github.com/LiskHQ/lisk/issues/2615
2. [x] Create Transaction entity with CRUD operations and unit tests  https://github.com/LiskHQ/lisk/issues/2616
2. [x] Create Peer entity with CRUD operations and unit tests https://github.com/LiskHQ/lisk/issues/2617
2. [x] Create Round entity with CRUD operations and unit tests https://github.com/LiskHQ/lisk/issues/2618
2. [x] Create Migration entity with CRUD operations and unit tests https://github.com/LiskHQ/lisk/issues/2619
7. [x] Replace `db.accounts.list`, `modules.accounts[.shared].get*` and `logic.account.get*`
with `storage.entieis.Account.get` https://github.com/LiskHQ/lisk/issues/2620
8. [x] Replace `db.transactions.list` and  `modules.transactions[.shared].get*`
with `storage.entieis.Transaction.get` https://github.com/LiskHQ/lisk/issues/2621
9. [x] Replace `db.blocks.list` and  `modules.blocks[.shared].list*`
with `storage.entieis.Transaction.get` https://github.com/LiskHQ/lisk/issues/2622
10. [x] Refactor `modules.accounts[.shared]` namespace https://github.com/LiskHQ/lisk/issues/2623
11. [x] Refactor `modules.transactions[.shared]` namespace https://github.com/LiskHQ/lisk/issues/2624
12. [x] Refactor `modules.blocks[.shared]` namespace https://github.com/LiskHQ/lisk/issues/2625
13. [x] Replace `db.migration` and move custom interfaces to `storage.entities.Migration` https://github.com/LiskHQ/lisk/issues/2626
14. [x] Replace `db.accounts` and move custom interfaces to `storage.entities.Account` https://github.com/LiskHQ/lisk/issues/2627
15. [x] Replace `db.transactions` and move custom interfaces to `storage.entities.Transaction` https://github.com/LiskHQ/lisk/issues/2628
16. [x] Replace `db.blocks` and move custom interfaces to `storage.entities.Block` https://github.com/LiskHQ/lisk/issues/2629
17. [x] Replace `db.rounds` and move custom interfaces to `storage.entities.Round` https://github.com/LiskHQ/lisk/issues/2630
18. [x] Replace `db.peers` and move custom interfaces to `storage.entities.Peer` https://github.com/LiskHQ/lisk/issues/2631
20. [x] Scan all modules to find interfaces which can be replaced by `storage.entities` https://github.com/LiskHQ/lisk/issues/2632

**Comment by MaciejBaj** [comment]
👏
