### ISSUE TITLE
Introduce new flexible, resilient and modular architecture - reference list

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2848]
These are the main items to address in this phase: 
- Have proper file structure in place 
- The configuration aligned with module structure 
- The code for modules to be decoupled (http-api)
- Easy prototyping any blockchain application

Continuation of this section will be followed by https://github.com/LiskHQ/lisk/issues/3022. 

#### Structure
- [x] Restructure the file directories for components, modules and framework files #2762
- [x] Migrate Lisk Modular repository files to framework directory and create lisk-chain module #2763

#### UX
- [x] Improve the UX/DX for creating a module for framework #2863

#### Refactoring
- [x] Refactor the event model and remove source from event #2912
- [x] Refactor the action layer for modules to load the actions directly not just names #2913
- [x] Refactor and verify the application cleanup logic for different cases #2914
- [x] Update the temp directory structure suitable for deployment #2849

#### Validation
- [x] Create controller/schemas/genesisBlock.js to validate genesis block #2884
- [x] Create controller/schemas/constants.js to validate system-wide constants #2889
- [x] Update config/default/constants.js to only accept strings and integers instead of Date object #2889

#### Multiprocess
- [x] Update bus to support RPC connections and relevant channel should be introduced https://github.com/LiskHQ/lisk/issues/3013
- [x] Load http_api module as a child process #3059

#### Documentation
- [x] Review and compile the JSDoc for framework #2845
- [x] Review README and validate CLI options #2974 #3115 #3123 
- [x] Update README file to reflect the modular architecture changes #3075

#### Testing
- [x] Move Mocha tests to a separate folder #2847 
- [x] Istanbul throws "Transformation error" exceptions #2858  
- [x] Import test suite structure from lisk-modular #2838
- [x] Add unit tests for framework codebase #2839
- [x] Run mocha tests by npm scripts & Remove Gruntfile.js #2935
- [x] Add jest tests to CI pipeline #2946
- [x] Remove sequential tags from tests and Fix conflicting tests #3089 
- [x] Add missing functional:put tests on Jenkins #3060
- [x] Functional test code coverage is broken #3100
- [x] Review http_api module unit test coverage #2988

#### Dependencies 
- [x] Update docker configuration to match with current structure #3039 
- [x] Update lisk scripts to work along new structure #3041

## Chain Module 
- [x] Refactor the chain module initialization to simplify and maintainable #2866
- [x] Refactor the logic of all transaction files to have consistent dependencies  #2779 

## HTTP API module
- [x] Resolve the conflicting responsibilities between api/controller and module of Delegates #2782 
- [x] Extract all API related codebase to a module named “http_api” #2770
- [x] Initialize the storage, logger and cache components separately #2771
- [x] Load the “http_api” module through controller #2772
- [x] Update the configuration files to group all configuration of HTTP API module #273
- [x] Integrate “signatures” posting communication with chain module #2774
- [x] Integrate “transactions” posting communication with chain module #2775
- [x] Integrate “peers” fetching communication with chain module #2776
- [x] Update fix all functional post tests for API #2777
- [x] Update fix all functional get tests for API #2778
- [x] Implement pending unit tests for HTTP API module #2988

## Storage Component 
- [x] Update Account entity to have only getters and move other functions to chain specific implementation #2764
- [x] Update Block entity to have only getters and move other functions to chain specific implementation #2765
- [x] Update Transaction entity to have only getters and move other functions to chain specific implementation #2766
- [x] Move Migration entity to chain module only #2767
- [x] Move Round entity to chain module only #2768
- [x] Move Peer entity to chain module only #2769
- [x] Storage component files should be exported via a predefined interface #2945
