### ISSUE TITLE
Prevent sync slowdown after receiving unconfirmed transactions

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#289]
Unconfirmed transactions are added to the memory pool when syncing. This is not very efficient and causes a serious performance impact on syncing as each transaction has to be undone and reapplied for each block.

**Tasks**

- [x] Do not add unconfirmed transactions when syncing
- [x] Undo unconfirmed transactions before sync
- [x] Receive saved unconfirmed transactions after sync
