### ISSUE TITLE
Improve blocks processing efficiency

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#449]
Block processing is not so efficient and logic is not perfect currently - because of that there are many possible issues and bottlenecks. Since it prevents us from expanding network and features - time to improve that.

- [x] SQL performance & flexibility #482
  - [x] Review queries and test their performance, find slow queries/views
    - [x] Improve performance for existing queries/view (if needed)
  - [x] Review data types performance & consistency

Connected issues:

- Node forked and didn't rolled back https://github.com/LiskHQ/lisk/issues/324
- Syncing from scratch randomly slows down https://github.com/LiskHQ/lisk/issues/352

Removed tasks:

- ~Review use of sequences (db, balance) #538~ (Cancelled)
- ~Refactor round logic #543~ (Cancelled)
- ~Redesign accounts ledger #544~ (Cancelled)
- ~Rewrite transaction pool #561~ (Cancelled) 
- ~Integrate new accounts ledger and transaction pool #972~ (Cancelled)
- ~Improve blocks related logging #539~ (Cancelled)

Previously connected issues:

- ~Achieve atomic block save #302~
- ~Refactor blocks module to submodules #534~
- ~Reload sometimes cause blockchain rebuild https://github.com/LiskHQ/lisk/issues/411~
- ~Why is mem_round flushed twice while finishing a round https://github.com/LiskHQ/lisk/issues/216~
- ~Improving network synchronisation - decentralised blockchain snapshots https://github.com/LiskHQ/lisk/issues/235~
- ~Improve block replication https://github.com/LiskHQ/lisk/issues/333~
- ~Add information about slot to blocks https://github.com/LiskHQ/lisk/issues/348~
- ~Tracking of missed blocks https://github.com/LiskHQ/lisk/issues/349~
- ~Networks lose stability when broadcasting transactions https://github.com/LiskHQ/lisk/issues/339~
- ~Round arithmetic is using standard Math functions https://github.com/LiskHQ/lisk/issues/447~
- ~Review block verification logic #459~
- ~Consistency when dealing with timestamps https://github.com/LiskHQ/lisk/issues/448~

**Comment by karmacoma** [comment]
@4miners I've revised the above mother issue with links to the associated child issues, plus marked our current progress.

**Comment by karmacoma** [comment]
Nested points are now stored in child issues.

**Comment by Isabello** [comment]
#541 and #459 have been reopened and require some additional work to be performed.

**Comment by karmacoma** [comment]
Issue closed #459.

**Comment by karmacoma** [comment]
Detached #302 from this issue. Therefore work complete.
