### ISSUE TITLE
Add unit test coverage of all blocks related logic and modules

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#456]
We should add unit tests for the following blocks related modules:

- [x] https://github.com/LiskHQ/lisk/blob/development/logic/account.js
- https://github.com/LiskHQ/lisk/blob/development/logic/block.js
- [x] https://github.com/LiskHQ/lisk/blob/development/logic/transaction.js
- [x] https://github.com/LiskHQ/lisk/blob/development/modules/accounts.js
- https://github.com/LiskHQ/lisk/blob/development/modules/blocks.js
- https://github.com/LiskHQ/lisk/blob/development/modules/transactions.js

We need to further add unit tests for all transaction types like:

- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/transfer.js
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/vote.js
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/dapp.js - Child issue: #841
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/delegate.js
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/signature.js - Child issue: #827
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/multisignature.js - Child issue: #832
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/inTransfer.js
- [x]  https://github.com/LiskHQ/lisk/blob/development/logic/outTransfer.js - Child Issue: #844 

Belongs to: #449

**Comment by yacineMTB** [comment]
:|

**Comment by SargeKhan** [comment]
We need to further add unit tests for all transaction types like:

- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/transfer.js
- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/vote.js
- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/delegate.js
- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/signature.js
- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/multisignature.js
- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/inTransfer.js
- [ ] https://github.com/LiskHQ/lisk/blob/development/logic/outTransfer.js

**Comment by MaciejBaj** [comment]
Tests skeletons to missing modules would be helpful to get the actual tests implemented
