### ISSUE TITLE
Redesign accounts ledger

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#544]
Belongs to: #449

Task List:

*Schema Changes*
- [x] Create new table `accounts` for store of immutable data about accounts, should contains following fields:
`"transaction_id" VARCHAR(20) NOT NULL REFERENCES transactions(id) ON DELETE CASCADE` - That reference transaction that created account, so when that transaction is deleted due to rollback - account will be also deleted
`"public_key_transaction_id" VARCHAR(20) DEFAULT NULL REFERENCES transactions(transaction_id) ON DELETE SET NULL` - That references transaction that created `public_key`
`"public_key" BYTEA DEFAULT NULL`
`"address"  VARCHAR(22) NOT NULL UNIQUE PRIMARY KEY` - Here we have some issue because real address can be max 21 chars, but we already have 22 chars addresses - to research
`"balance" BIGINT DEFAULT 0`
  - [x] Add proper indexes

- [x] Remove old tables: `mem_accounts`, `mem_accounts2*`
  - [x] Replace `mem_accounts2delegates` with `delegates` table
  - [x] Replace `mem_accounts2multisignatures` with `multisignature_master` table
  - [x] Split column `mem_accounts2multisignatures.keysgroup` to be `multisignature_member` table, with relations to `multisignature_master.public_key` using `master_public_key`

- [x] Create new view, `accounts_list` to provide abstraction for `GET` requests

- [x] Add `public_key` field to following tables: `second_signature`, `votes`, `multisignature_master` `multisignature_member`, `dapps`, `intransfer`, `outtransfer` - so we can do easy joins with them on `public_key`, ensure proper foreign keys (also `delegates` table need to be reviewed)

- [x] Propagate `accounts` table from blockchain data
  - [x] Migrate balances from transactions
    - [x] Migrate rewards/fees from rounds_rewards

*Trigger changes or additions*

- [x] Write trigger that will set `public_key` to NULL when `public_key_transaction_id` is set to `NULL`
- [x] Write triggers on `transactions` table that will maintain state of `accounts` table fields - `AFTER INSERT`
	- [x] ALL: Check sender - update `public_key` field if it's NULL, update balance `-(fee+amount)`
	- [x] TRANSFER - Check recipient - create account if not exists and update balance `+amount`
	- [x] SIGNATURE - Update `second_public_key` if it's `NULL` // skipped - we will try to use existing signature table
- [x] Write triggers on `transactions` table that will maintain state of `accounts` table in case of rollback - `BEFORE DELETE` or maybe `AFTER DELETE` (to research)
	- [x] ALL: Check sender, update balance `+(fee+amount)`, scan `transactions` table if 
	- [x] TRANSFER - Check recipient - update balance `-amount`

*Code Changes*
- [x] Refactor existing application logic to support new table and relations
  - [x] Alter all `dbSave` functions to be aware of new schema
  - [x] API endpoints and related list functions1
  - [X] Dealing with confirmed
    - [x] Create account by transaction insert (Covered in triggers)
  - [x] Remove `apply*`, `undo*`, etc. that affects balances only, transaction types should be preserved
- [x] Refactor `delegates_update_on_block` and dependent functions such as `delegates_voters_balance_update` (rounds rewrite thing) to benefit from `accounts` table - should be easy and fast to generate changes from current round transactions and merge them with `accounts.balance`
- [x] Remove undoUnconfirmed that use accounts.merge
- [x] Remove apply functions that use accounts.merge
- [x] Remove undo functions that use accounts.merge
- [x] Remove applyUnconfirmed functions that use accounts.merge
- [x] Remove account.set
- [x] Remove account.merge
- [x] Refactor setAccountAndGet
  - [x] Accept transaction to pull properties from
  - [x] Rename setAccountAndGet to getSender

Tests:
- [x] Adjust tests
  - [X] HTTP Post
  - [x] HTTP Get
  - [x] Unit tests

- [x] Write new tests
  - [x] Accounts sql
  - [x] HTTP Post - Check 0 balance

**Comment by 4miners** [comment]
Task list:
- [ ] Create new table `accounts` for store of immutable data about accounts, should contains following fields:
`"tx_id" VARCHAR(20) NOT NULL REFERENCES trs(id) ON DELETE CASCADE` - That reference transaction that created account, so when that transaction is deleted due to rollback - account will be also deleted
`"pk_tx_id" VARCHAR(20) DEFAULT NULL REFERENCES trs(id) ON DELETE SET NULL` - That references transaction that created `pk`
`"pk" BYTEA DEFAULT NULL`
`"second_pk" BYTEA DEFAULT NULL`
`"address"  VARCHAR(22) NOT NULL UNIQUE PRIMARY KEY` - Here we have some issue because real address can be max 21 chars, but we already have 22 chars addresses - to reaseach
`"balance" BIGINT DEFAULT 0`
Because account can be created in 2 possible ways - either send funds to address or send funds to account public key (future usage, that will also fill address field because address is delivered from pk) - so we still define `address` as `NOT NULL UNIQUE PRIMARY KEY`.
  - [ ] Propagate `accounts` table from blockchain data
  - [ ] Write trigger that will set `pk` to NULL when `pk_tx_id` is set to `NULL`
  - [ ] Write triggers on `trs` table that will maintain state of `accounts` table fields - `AFTER INSERT`
    - ALL: Check sender - update `pk` field if it's NULL, update balance `-(fee+amount)`
    - TRANSFER - Check recipient - create account if not exists and update balance `+amount`
    - SIGNATURE - Update `second_pk` if it's `NULL`
  - [ ] Write triggers on `trs` table that will maintain state of `accounts` table in case of rollback - `BEFORE DELETE` or maybe `AFTER DELETE` (to research)
    - ALL: Check sender, update balance `+(fee+amount)`, scan `trs` table if 
    - TRANSFER - Check recipient - update balance `-amount`
    - SIGNATURE - Set `second_pk` to `NULL`
  - [ ] Add proper indexes (to research)
- [ ] Add `pk` field to following tables: `signatures`, `votes`, `multisignatures`, `dapps`, `intransfer`, `outtransfer` - so we can do easy joins with them on `pk`, ensure proper foreigns keys (also `delegates` table need to be reviewed)
- [ ] Refactor existing application logic to support new table and relations
  - [ ] API endpoints and related list functions
  - [ ] Add `pk` field when push transaction types
  - [ ] When we rollback a block - deleted transactions should go back to pool (as verified)
  - [ ] Dealing with confirmed
    - We don't need to worry about accounts creation/deletion and balances update but remember to take care about dealing with transaction types
    - [ ] When we receive new block that contains transactions - we shouldn't need to validate included transactions against accounts state but just push block to postgres and get status (block as an immutable object can be either valid or invalid) - proper relations and checks on tables should ensure data integrity (like `CHECK (balance > 0`). However that can be difficult on our existing database because of exceptions that we already have - to research.
      - If that cannot be done or is too difficult - we need to validate block transactions against accounts states.
    - [ ] Before we forge a block - we need to validate transactions agains accounts state, that can be done in 2 different ways:
       - Write SQL queries or function that will check things and return us simple `true` or `false` (or reason) as a result, so we can just push pack of transactions to postgres and get results which ones are valid against accounts state (preferred). It can be difficult as above because of exceptions.
       - Keep current behavior - get accounts from database and validate against it.
  - [ ] Dealing with unconfirmed
      - As stated in #561 - unconfirmed states will be removed, however we still have some options here and some research is needed:
        - Check against confirmed only just before forge a block (when we including txs into block)
        - Check against confirmed states when we receive transaction
        - Check against confirmed states when we receive transaction and after every new block
  - [ ] Remove `apply*`, `undo*`, etc. that affects balances only, transaction types should be preserved 
- [ ] Remove old tables: `mem_acocunts`, `mem_accounts2*`

**Comment by 4miners** [comment]
https://github.com/LiskHQ/lisk/issues/457 should be done first.
