### ISSUE TITLE
Apply lisk-template repository

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#672]
We should apply the `lisk-template` repository created by @LiskHQ/standards to this repository. This will align it with the newly defined standards, patterns and workflows that will be applied to all new and existing repositories from now on.

### Todo

- [x] Update .nvmrc - #1204
- [x] .editorconfig file - #1202
- [x] .npmrc file - #1203
- [x] License header in every file - #680 
- [x] Standardize .gitignore file - #1237 
- [x] Standardize package.json fields - #1215
- [x] Standardize npm scripts - #1218
- [x] Documents for contributors - #1205
- [x] Standardize Jenkinsfiles, setup snyk etc - #1219
- [x] Standardize mocha/chai/sinon setup (e.g. sandbox) - #1216 
- [x] Standardize package manager - #1355 

#### After everything else

- [x] Be consistent about use of `should` vs `expect` - #1295 
- [x] underscore_separated file/directory names - #1221
- [x] ESLint - #1207
- [x] Prettier - #1206
- [x] Husky and lint-staged #1213
- ~US English - #1220~
- ES6+, babel etc

#### After 1.0.0

~~Standardize nyc setup - #1217~~
~~Standardize Coveralls setup - #1253~~

**Comment by willclarktech** [comment]
@karmacoma This issue should be left until closer to the `1.0.0` release, correct?

**Comment by GuilhermeMedeiros** [comment]
why not prettier? I've been using it on all my projects and I really like it.
you can setup prettier with eslint and have some extra stuff if you will

**Comment by karmacoma** [comment]
@willclarktech This is correct

**Comment by karmacoma** [comment]
@GuilhermeMedeiros We will take a look into it, thanks for the suggestion.

**Comment by willclarktech** [comment]
I've not used prettier, but my experience with [elm-format](https://github.com/avh4/elm-format) is entirely positive.

**Comment by karmacoma** [comment]
Title and description updated to reflect the work being done by @LiskHQ/standards.

**Comment by willclarktech** [comment]
@karmacoma I suggest making this a parent issue so we can create smaller issues for each (relevant) aspect of lisk-template.

**Comment by karmacoma** [comment]
@willclarktech Done. Please feel free to create a task list of child issues.

**Comment by karmacoma** [comment]
Thanks for your efforts @willclarktech @ManuGowda. Excellent work 👍
