### ISSUE TITLE
Migration path to 1.0.0 from 0.9.x

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#675]
With the upcoming release of Lisk-Core 1.0.0, the HTTP P2P stack will be obsoleted and removed. However, in order to migrate from HTTP P2P stack to the WS P2P stack, we must keep allow communications between 0.9.x and 1.0.0. The scope of this communication should be severely limited. 

The implementation of this should follow this design:

Limited HTTP p2p stack
POST /peers/blocks - Required to submit blocks to other nodes
GET /peers/blocks - Required to acquire blocks from other nodes
GET /blocks/common - To sync blocks
GET /peers/height - Required to maintain peer state
GET /peers/ping - As above

Each of these pieces of functionality will be required in an interim release to maintain the bridge between the live networks, and to prevent transactions from being lost on the old network, or double spent on both networks. This release will last for approximately 1-2 weeks giving node operators and other services the chance to migrate to the new version.

To prevent the data field from causing issues, a milestone will be used to prevent network splittage ahead of the cutover.

_Old ideas: (Graveyard):_
- Overtake all delegates and freeze the network for transition
- Set a kill block in 0.9.3 code and kill the old network creating a clean cut over point to create a new genesisBlock on the new network
- Run both 0.9.x and 1.0.0 clients on the same node, using the kill block concept above to engage the new network gracefully

---

Task List:

- [x] Implement Network-Bridge for migration https://github.com/LiskHQ/lisk-build/issues/176
- [x] Add support for Lisky https://github.com/LiskHQ/lisk-build/issues/183
- [x] Implement delegate passphrase encryption https://github.com/LiskHQ/lisky/issues/29
- ~~Allow plaintext passphrases in the config.json #712~~
- [x] Create migration Jenkins build from 0.9.x to 1.0.0 #1095

**Comment by pcdinh** [comment]
@Isabello Any ETA for LISK 1.0.0? We should make as much noise as possible about LISK 1.0.0 changes 2-3 weeks  before the release to ensure that nobody will be surprised

**Comment by Isabello** [comment]
I cannot provide an ETA at this time. This issue is for discussing how the migration should be done and the required changes to accomodate it.

**Comment by karmacoma** [comment]
Added a task list to the issue description.
