### ISSUE TITLE
Support for several package managers

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#687]
Most people from the team are using **_yarn_** instead of _npm_ due to speed and deterministic reasons. https://blog.risingstack.com/yarn-vs-npm-node-js-package-managers/ . Lisk-js and lisky repos are already using it.
On the other side, last stable version of _npm_ is introducing `package-lock.json` which it is a best practice too.

We should commit lockfiles in all our repositories as a must. https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

I propose : 
- [x] update _npm_ to v5 & add `package-lock.json`
- [x] update yarn & add `yarn.lock`
- [x] check if both package managers might coexist
- [X] specify maximum version of NPM 5 allowed - #897 
- ~~include some notes in the readme on how to use the package managers~~

**Comment by willclarktech** [comment]
Two downsides of supporting both `npm` and `yarn`:
1. Adding a new package requires the adder to (remember to) run both `npm install` and `yarn add`.
1. Since there's no guarantee `package-lock.json` and `yarn.lock` will be equivalent, supporting both reduces the benefit of having lockfiles at all (the main point being that we would know everyone's dependencies would be in the same situation).

**Comment by Tschakki** [comment]
Good points!
I found an issue at the yarn repo that is addressing this problem: https://github.com/yarnpkg/yarn/issues/3614

Since this issue is solved, we should maybe support only one lockfile

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk/commit/ca5ea4f3321b24feb6649bc23f9a0ec6373ed9a0
