### ISSUE TITLE
Reducing execution test time

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#809]
We have identified several points which drain a lot of time when executing the test-suite. I propose solutions to reduce this wait:

- [x] unit blocRewards : isolate unit blockRewards test to run in parallel within Jenkins (PR #810)
- [x] exclude slow test through slow mocha tag : currently there are two test (delegates cache flush and stress) which take 17 minutes each one. We tag them to avoid its execution day-to-day (PR #811)
- [x] create a new Jenkins nightly job to include slow test : It will be available to launch it manually and also executed nightly. For now, it won't be required to merge PR until we have better solutions. (PR #813)
- [x] review build dependencies phase (PR #814)
