### ISSUE TITLE
Jenkins full performance review

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#851]
With the aim of achieving a more professional development and testing environment, I propose a task list to organise, clean and improve the performance of our testsuite.
- [x] Execute every testsuite through npm scripts handling test by `index.js` files #852
- [x] Reorganise job handling by the existing set of nodes #852
- [x] Review grunt #874
- [x] Review coverage #874
- [x] Functional tests executed in separate processes #863
