### ISSUE TITLE
Swagger Integration with Core

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#899]
Belongs to: #225 

Right now we are managing schema of all our APIs in json-schema formats within app. And then defining same schema again in swagger. That's make redundant code. 

Need changes in following: 
1. API loading and endpoint registration
2. Parameter validations 
3. Response validations 

So the definition in Swagger should only be used. 

Related Task List:

- [x] Configure Swagger Runner with the application #918
- [x] Add Swagger Based Response Validation in Test Cases #919
- [x] Move existing express middleware to swagger-runner pipelines #1011 
- [x] Standarisation of swagger responses #674 

Endpoint Task List:

- [x] accounts #920 
- [x] blocks #921 
- [x] dapps #922 
- [x] delegates #923 
- [x] multisignatures
  - [x] multisignature-accounts #1116 
  ~~- [ ] multisignature-pending~~ https://github.com/LiskHQ/lisk/issues/899#issuecomment-350706885
- [x] node #924 
- [x] peers #925 
- [x] signatures #926 
- [x] transactions #927 
- [x] votes #928 
- [x] voters #929

**Comment by nazarhussain** [comment]
@karmacoma I looked over the code and found these two endpoints, still not implemented.

```
GET /api/multisignatures/pending
GET /api/multisignatures/accounts
```

For the second one, we have swagger documentation, so going to create its task. For the first one, please suggest. 

- [ ] multisig-accounts #1116
- [ ] multisig-pending-accounts

**Comment by nazarhussain** [comment]
Confirmed that `/api/multisignatures/pending`, is identical to new endpoint `/api/node/transactions/unsigned`. So remove this from task list.
