### ISSUE TITLE
Backport 0.9.10 changes to 1.0.0 

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#909]
According to the pull requests merged in `0.9.10`:

- ~~Move cb to last argument for blocks/chain/applyBlock~~
- [x] 0.9.10 - Multisig transactions from the same account bug resolution #1042 
- ~~Decreased amount of LSK transferred to multi account~~ 
- ~~Rewind fork 5-3 fix~~
- [x] Bug resolution for multisignature registration transaction #1000
- [x] Duplicated delegates fix with silent validation failure #1049

**Comment by MaciejBaj** [comment]
Moreover: 
- [ ] discard rounds generation changes from 0.9.10
- [ ] accept mem_accounts migration to allow nullify determined fields
- [ ] accept mem_accounts protection tests
- [ ] merge multisignature confirmation functional tests with existing ones
- [ ] merge delegates double registration tests with existing ones
- [ ] apply fork 1, 3, 5 unit tests
- [ ] apply new transaction sort order
- [ ] change the arguments order of verify.processBlock function
- [ ] adapt node.initApplication delegates generation functionalities
- [ ] use transactionPool from test application in unit tests
