### ISSUE TITLE
Decouple validation phase for functional test tx type 1 - Subtask #678

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#978]
Due to the increasing size and complexity of these tests, we decide to isolate validation phase into several files renaming them with smart tags:

- [x] Create folder for type 1 : adjust grunt task
- [x] Create "before" phase shareable
- [x] Isolate "validation" phase: several files addressing all different types of transactions on top of type 1 (1.0.transfer, 1.1.second.signature, and so on)
- [x] Increase use cases covered

Parent #678
